<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1545380501360" stop="1545380711825">
    <name>Default Suite</name>
    <test-cases>
        <test-case start="1545380521283" stop="1545380711784" status="failed">
            <name>testContactToGroupAddition</name>
            <failure>
                <message>AssertionError: 
Expected: &lt;[GroupData{grid=259, grname='Group_1545380509354', grheader='Group_new', grfooter='Group_new1'}, GroupData{grid=260, grname='Group_1545380526808', grheader='Group_new', grfooter='Group_new1'}]&gt;
     but: was &lt;[GroupData{grid=259, grname='Group_1545380509354', grheader='Group_new', grfooter='Group_new1'}]&gt;</message>
                <stack-trace>java.lang.AssertionError: 
Expected: &lt;[GroupData{grid=259, grname='Group_1545380509354', grheader='Group_new', grfooter='Group_new1'}, GroupData{grid=260, grname='Group_1545380526808', grheader='Group_new', grfooter='Group_new1'}]&gt;
     but: was &lt;[GroupData{grid=259, grname='Group_1545380509354', grheader='Group_new', grfooter='Group_new1'}]&gt;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at ru.mytest.addressbook.tests.ContactToGroupAdditionTests.testContactToGroupAddition(ContactToGroupAdditionTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
    </test-cases>
    <labels/>
</ns2:test-suite>
